name: UnitTest

on: [push]

jobs:
  build-and-upload:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, ubuntu-24.04-arm, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0"
      - name: build
        run: |
          dotnet build ./Pillar.Demystifier.slnx
      - name: test
        run: |
          dotnet test ./Pillar.Demystifier.slnx